name: Pipeline CI

on:
  push:
    branches:
    - main
    paths:
    - data/**


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main
    - name: Checkout exercise feedback
      uses: actions/checkout@v3
      with:
        repository: MaeenBadea/2023-amse-template
        path: ci
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Execute tests
      run: |
        ./ci/project/tests.sh
